##### REGISTER
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
    "email": "ronak01@example.com",
    "password": "mypassword123"
}


##### LOGIN
POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
    "email": "ronak01@example.com",
    "password": "mypassword123"
}


##### CREATE SHORT URL - AUTHENTICATED
POST http://127.0.0.1:5000/urls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4ODUzOTg3MywianRpIjoiODE5NWE0N2QtZjY4Mi00NGM1LWFjODktYzVlYzQxNTlmNTM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3ODg1Mzk4NzMsImNzcmYiOiJiODkzOTc3ZS0xNTQ1LTQ2MGUtOWRjZS0xZTkzM2U0NzVhYjciLCJleHAiOjE3ODg1NDM0NzN9.3jT_UoJWaaypZoX47dSoatnM1dom3Lznt9Jg-rLeQBs
Content-Type: application/json

{

    "original_url": "https://google.com"
}


### REDIRECT SHORT URL
GET http://127.0.0.1:5000/hiaJVi


#####
GET http://127.0.0.1:5000/abcdefg
